(function(){
  if(window.__AT_REMINDERS_DROPIN__) return;
  window.__AT_REMINDERS_DROPIN__=true;
  const COMPLETED_TASKS_KEY='at_manager_completed_tasks_v2';
  let taskMode='today';
  let taskDate='';
  let completedTasks=loadCompletedTasks();
  const $id=(id)=>document.getElementById(id);
  function loadCompletedTasks(){try{return new Set(JSON.parse(localStorage.getItem(COMPLETED_TASKS_KEY)||'[]'))}catch(e){return new Set()}}
  function saveCompletedTasks(){localStorage.setItem(COMPLETED_TASKS_KEY,JSON.stringify([...completedTasks]))}
  function taskKey(t){return [t.student.id,t.type,t.time].join('|')}
  function sameDay(a,b){const x=new Date(a),y=new Date(b);return x.getFullYear()===y.getFullYear()&&x.getMonth()===y.getMonth()&&x.getDate()===y.getDate()}
  function safeEsc(v){if(typeof esc==='function')return esc(v);return String(v||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
  function safeFmt(v){if(typeof fmt==='function')return fmt(v);const d=new Date(v);return isNaN(d)?String(v||''):`${d.getMonth()+1}/${d.getDate()} ${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`}
  function safeStatusName(s){return typeof statusName==='function'?statusName(s):(s||'')}
  function buildTasks(){const out=[];const now=new Date();(window.students||students||[]).forEach(s=>{const push=(type,action,time,urgent=false)=>{if(!time)return;const d=new Date(time);if(isNaN(d))return;out.push({student:s,type,action,time:d.toISOString(),sort:d.getTime(),urgent:urgent||d.getTime()<now.getTime()})};if(s.contactTime)push('指定聯絡','依指定時間聯絡客戶',s.contactTime,true);if(s.classTime){const ct=new Date(s.classTime);if(!isNaN(ct)){push('課前一天提醒','傳送課前提醒訊息',new Date(ct.getTime()-24*60*60*1000));push('課前 30 分鐘','確認學員是否可順利進教室',new Date(ct.getTime()-30*60*1000));push('課後 30 分鐘關懷','關心體驗課狀況',new Date(ct.getTime()+30*60*1000));push('優惠券到期提醒','提醒優惠券即將到期',new Date(ct.getTime()+22*60*60*1000));push('24H Log','完成課後 24 小時內紀錄',new Date(ct.getTime()+23*60*60*1000))}}});return out.sort((a,b)=>a.sort-b.sort)}
  function getTemplates(){try{return (typeof templates!=='undefined'&&Array.isArray(templates))?templates:(Array.isArray(window.templates)?window.templates:[])}catch(e){return Array.isArray(window.templates)?window.templates:[]}}
  function findTemplateByLabels(labels){const list=getTemplates();return labels.map(k=>list.find(t=>String(t.label||'').replace(/\s/g,'').includes(String(k).replace(/\s/g,'')))).find(Boolean)||null}
  function fallback24hText(s){return `📢 小提醒～我們 ${safeFmt(s.classTime)} 有一堂體驗課！\n\n教室會在課程開始前 10 分鐘開放，登入方式請選擇 ${s.loginType||'信箱/手機'} 登入唷～\n登入 AmazingTalker 後到首頁，找到待會要上的課程，點擊「進入教室」就可以上課囉！有空可以提早上去熟悉一下畫面唷～\n\n課後再麻煩幫我留個 10 分鐘，我會打電話關心一下上課的狀況。\n\n另外～老師會在課後送您一張「體驗課後 24 小時內完成購課」的折價券，可以直接在老師的對話框領取，搭配堂數折扣買課最划算！課後可以跟老師討論一下唷～\n\n💎 堂數折扣：\n• 單次購買 20 堂課或 20 堂的倍數：85 折（最優惠）\n• 單次購買 10 堂：9 折\n• 單次購買 5 堂：95 折\n\n如有需要調整請提早到系統內調整，確認上線沒問題也再麻煩留個貼圖給我唷～😉💖\n\nHelga`}
  window.copyReminderMessage=function(studentId,type){const list=window.students||students||[];const s=list.find(x=>String(x.id)===String(studentId));if(!s)return;let tpl=null;if(type==='課前一天提醒')tpl=findTemplateByLabels(['課前24小時完整提醒','課前24小時','24小時完整提醒']);else if(type==='課前 30 分鐘')tpl=findTemplateByLabels(['課前30分鐘自我提醒','課前30分鐘']);else if(type==='課後 30 分鐘關懷')tpl=findTemplateByLabels(['課後30分鐘關懷','課後關懷']);else if(type==='優惠券到期提醒')tpl=findTemplateByLabels(['課後22小時優惠券到期提醒','優惠券到期提醒']);else if(type==='24H Log')tpl=findTemplateByLabels(['課後24小時跟進','24H','24小時跟進']);else if(type==='指定聯絡')tpl=findTemplateByLabels(['課後24小時跟進','優惠促轉訊息','課前預約確認']);if(tpl&&typeof applyTemplate==='function'&&typeof copyText==='function'){copyText(applyTemplate(tpl.text,s));return}if(type==='課前一天提醒'&&typeof copyText==='function'){copyText(fallback24hText(s));return}if(typeof copyForStudent==='function')copyForStudent(studentId)};
  window.setTaskMode=function(mode){taskMode=mode;if(mode!=='date'){const d=$id('taskDatePicker');if(d)d.value=''}renderTasks()};
  window.setTaskDate=function(v){taskDate=v||'';taskMode='date';renderTasks()};
  window.completeTask=function(key){completedTasks.add(key);saveCompletedTasks();renderTasks();if(typeof showToast==='function')showToast('已完成提醒')};
  window.clearCompletedTasks=function(){if(!confirm('確定清除已完成提醒紀錄？'))return;completedTasks.clear();saveCompletedTasks();renderTasks();if(typeof showToast==='function')showToast('已清除')};
  window.renderTasks=function(){const el=$id('tasksList');if(!el)return;const today=new Date(),tomorrow=new Date(Date.now()+24*60*60*1000);let tasks=buildTasks().filter(t=>!completedTasks.has(taskKey(t)));if(taskMode==='today')tasks=tasks.filter(t=>sameDay(t.time,today));if(taskMode==='tomorrow')tasks=tasks.filter(t=>sameDay(t.time,tomorrow));if(taskMode==='date'&&taskDate)tasks=tasks.filter(t=>sameDay(t.time,new Date(taskDate+'T00:00:00')));if(!tasks.length){el.innerHTML='<div class="empty">目前沒有提醒待辦</div>';return}el.innerHTML=tasks.map(t=>{const sid=String(t.student.id||'').replace(/'/g,"\\'");const key=taskKey(t).replace(/'/g,"\\'");const typ=String(t.type||'').replace(/'/g,"\\'");return `<div class="card" style="border-left:4px solid ${t.urgent?'#D85A30':'var(--brand)'}"><div class="card-head"><div><div class="name">${safeEsc(t.student.name)}｜${safeEsc(t.type)}</div><div class="small">${safeFmt(t.time)} ${t.urgent?'｜已到期或需優先處理':''}</div></div><div class="status s-${safeEsc(t.student.status)}">${safeStatusName(t.student.status)}</div></div><div class="note">${safeEsc(t.action)}</div><div class="actions"><button class="btn btn-line" onclick="copyReminderMessage('${sid}','${typ}')">複製訊息</button><button class="btn btn-cal" onclick="addToCalendar('${sid}')">加日曆</button><button class="btn btn-second" onclick="openModal('${sid}')">看學員</button><button class="btn btn-del" onclick="completeTask('${key}')">完成</button></div></div>`}).join('')};
  function ensureUI(){const tabs=document.querySelector('.tabs');if(!tabs)return false;if(!document.querySelector('.tab[data-view="tasks"]')){const tab=document.createElement('div');tab.className='tab';tab.dataset.view='tasks';tab.textContent='提醒';tabs.prepend(tab)}if(!$id('tasksView')){const list=$id('listView');if(!list)return false;const sec=document.createElement('section');sec.id='tasksView';sec.style.display='none';sec.innerHTML=`<div class="card"><div class="section-title" style="margin-top:0">提醒待辦</div><div class="hint">依體驗課時間與指定聯絡時間自動產生。已過期或接近時間的事項會排在前面。</div><div class="actions"><button class="btn btn-second" onclick="setTaskMode('today')">今天</button><button class="btn btn-second" onclick="setTaskMode('tomorrow')">明天</button><button class="btn btn-second" onclick="setTaskMode('all')">全部</button><input id="taskDatePicker" type="date" onchange="setTaskDate(this.value)" style="padding:8px 10px;border:1px solid #DDD6C5;border-radius:7px;font-size:13px"><button class="btn btn-del" onclick="clearCompletedTasks()">清除已完成紀錄</button></div></div><div id="tasksList"></div>`;list.parentNode.insertBefore(sec,list)}document.querySelectorAll('.tab').forEach(t=>{t.onclick=function(){window.currentView=t.dataset.view;try{currentView=t.dataset.view}catch(e){}document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===t));['tasks','list','templates','pomodoro','settings'].forEach(v=>{const el=$id(v+'View');if(el)el.style.display=t.dataset.view===v?'block':'none'});const fab=document.querySelector('.fab');if(fab)fab.style.display=t.dataset.view==='list'?'block':'none';if(t.dataset.view==='tasks')renderTasks();else if(typeof render==='function')render();if(t.dataset.view==='settings'&&typeof populateSettings==='function')populateSettings()}});return true}
  const timer=setInterval(()=>{if(ensureUI()){clearInterval(timer);if((window.currentView||'')==='tasks')renderTasks()}},200);
})();
